# Generated by Django 4.2.5 on 2023-10-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forget_password_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
