# Generated by Django 4.2.5 on 2023-10-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0002_customuser_forget_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_doctor',
            field=models.BooleanField(default=False, null=True, verbose_name='is_doctor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_patient',
            field=models.BooleanField(default=False, null=True, verbose_name='is_patient'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Patient', 'Patient'), ('Doctor', 'Doctor')], default='Doctor', max_length=15),
        ),
    ]
