# Generated by Django 4.2.5 on 2023-10-28 07:15

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0004_alter_customuser_is_doctor_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_doctor',
            field=models.BooleanField(default=False, null=True, verbose_name='is_doctor'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_patient',
            field=models.BooleanField(default=False, null=True, verbose_name='is_patient'),
        ),
    ]
