# Generated by Django 4.2.5 on 2023-10-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0010_medicine_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
