# Generated by Django 4.2.5 on 2023-11-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0014_remove_doctordetails_degrees_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorDetails',
        ),
    ]
