# Generated by Django 4.2.5 on 2023-11-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0018_consultationrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsultationRequest',
        ),
    ]
