# Generated by Django 4.2.5 on 2023-11-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0022_onlineconsultation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineConsultation',
        ),
    ]
