# Generated by Django 4.2.5 on 2023-11-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0026_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
