# Generated by Django 4.2.5 on 2023-11-06 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0027_delete_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot', models.CharField(choices=[('9:00 AM - 10:00 AM', '9:00 AM - 10:00 AM'), ('10:00 AM - 11:00 AM', '10:00 AM - 11:00 AM'), ('11:00 AM - 12:00 PM', '11:00 AM - 12:00 PM'), ('12:00 PM - 1:00 PM', '12:00 PM - 1:00 PM'), ('2:00 PM - 3:00 PM', '2:00 PM - 3:00 PM'), ('3:00 PM - 4:00 PM', '3:00 PM - 4:00 PM'), ('4:00 PM - 5:00 PM', '4:00 PM - 5:00 PM'), ('5:00 PM - 6:00 PM', '5:00 PM - 6:00 PM'), ('6:00 PM - 7:00 PM', '6:00 PM - 7:00 PM')], max_length=30)),
                ('patient_name', models.CharField(max_length=60)),
                ('patient_email', models.EmailField(max_length=254)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allapp.patient')),
            ],
        ),
    ]
