# Generated by Django 4.2.5 on 2023-11-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0032_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
