# Generated by Django 4.2.5 on 2023-11-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0034_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
