# Generated by Django 4.2.5 on 2024-02-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0037_clinic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clinic',
        ),
    ]
