# Generated by Django 4.2.5 on 2024-02-29 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0042_thread_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clinic',
        ),
    ]
