# Generated by Django 4.2.5 on 2024-02-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0043_delete_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('speciality', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='clinic_images/')),
                ('doctors', models.ManyToManyField(blank=True, to='allapp.doctor')),
            ],
        ),
    ]
