# Generated by Django 4.2.5 on 2024-03-01 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0044_clinic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositiveTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='allapp.testimonial')),
            ],
        ),
        migrations.CreateModel(
            name='NegativeTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='allapp.testimonial')),
            ],
        ),
    ]
