# Generated by Django 4.2.5 on 2024-03-01 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0045_positivetestimonial_negativetestimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positivetestimonial',
            name='testimonial',
        ),
        migrations.DeleteModel(
            name='NegativeTestimonial',
        ),
        migrations.DeleteModel(
            name='PositiveTestimonial',
        ),
    ]
