# Generated by Django 4.2.5 on 2024-03-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0046_remove_positivetestimonial_testimonial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_slot',
            field=models.CharField(choices=[('10:00 AM - 11:00 AM', '10:00 AM - 11:00 AM'), ('12:00 PM - 1:00 PM', '12:00 PM - 1:00 PM'), ('2:00 PM - 3:00 PM', '2:00 PM - 3:00 PM'), ('4:00 PM - 5:00 PM', '4:00 PM - 5:00 PM'), ('6:00 PM - 7:00 PM', '6:00 PM - 7:00 PM')], max_length=30),
        ),
    ]
