# Generated by Django 4.2.5 on 2024-03-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0048_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
