# Generated by Django 4.2.5 on 2024-03-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0049_remove_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='medicine',
        ),
    ]
