# Generated by Django 4.2.5 on 2024-03-28 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allapp', '0051_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
